# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    #!/bin/bash

    # Download xoreos-tools
    git clone git://github.com/xoreos/xoreos-tools

    sudo apt-get update
    sudo apt-get install unzip

    # Download files from Google Drive
    wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=18CUUm7kTGmEsapCVxAdSvHL3yM0KU5yb' -O scripts.zip
    unzip scripts.zip

    # Set permissions on scripts to make them runnable
    chmod 777 setup.sh mingw32-8.3 mingw_inst.sh crosscompilexoreos.sh
    dos2unix setup.sh mingw32-8.3 mingw_inst.sh crosscompilexoreos.sh
    # Run the setup script
    ./setup.sh

    # Cross compile
    ./crosscompilexoreos.sh xoreos-tools
    

  displayName: 'Build xoreos-tools for Ubuntu'