# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    #!/bin/bash

    # Download xoreos-tools
    git clone git://github.com/xoreos/xoreos-tools

    # Update apt-get
    sudo apt-get update

    
    # Download files from Google Drive

    sudo apt-get install -y python3-pip
    pip3 install setuptools
    pip3 install wheel
    pip3 install gdown
    sudo apt-get install unzip
    
    /home/${USER}/.local/bin/gdown -O scripts.zip 'https://docs.google.com/uc?id=18CUUm7kTGmEsapCVxAdSvHL3yM0KU5yb'
    unzip scripts.zip

    # Set permissions on scripts to make them runnable
    chmod 777 setup.sh mingw32-8.3 mingw_inst.sh crosscompilexoreos.sh

    # Convert the line endings
    sudo apt-get install dos2unix
    dos2unix setup.sh mingw32-8.3 mingw_inst.sh crosscompilexoreos.sh
    # Run the setup script
    ./setup.sh

  displayName: 'Setup pre-requisites for xoreos-tools'

- script: ./crosscompilexoreos.sh xoreos-tools
  displayName: 'Cross-compile xoreos-tools'

- script: |
    # Zip up the files
    zip -o release.zip /home/$USER/RELEASEBIN
    
    # Upload the files to Azure storage
    - bash: az storage blob upload --container-name builds --file test.txt --name test.txt --account-name xoreosbuilds --account-key yOVxXLuFb1urs9wuPUpMdKr3gBVFJ8h/YJm5ySld5wMWkwW8PCi0qPoKKf21RPYEdFg2XeS/lpPGbhz3fpG8Hg==

    azcopy --source release.zip --destination 'https://xoreosbuilds.blob.core.windows.net/builds/release.zip'

  displayName: 'Save to Azure storage account'
